src/main/default/objects/Contact/fields/Mascot__c.field-meta.xml
<CustomField>
    <fullName>Mascot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mascot</label>
    <referenceTo>Mascot__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Mascot__c/Mascot__c.object-meta.xml
<CustomObject>
    <description>Helper critters here to help you succeed with Salesforce!</description>
    <label>Mascot</label>
    <nameField>
        <label>Mascot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mascots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/Mascot__c/fields/Biography__c.field-meta.xml
<CustomField>
    <fullName>Biography__c</fullName>
    <label>Biography</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

src/main/default/objects/Mascot__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Mascots</relationshipLabel>
    <relationshipName>Mascots</relationshipName>
    <type>Lookup</type>
</CustomField>

src/main/default/objects/Mascot__c/fields/Picture__c.field-meta.xml
<CustomField>
    <fullName>Picture__c</fullName>
    <formula>IMAGE( &#39;/sfc/servlet.shepherd/version/download/&#39;+Picture_Id__c , Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Picture</label>
    <type>Text</type>
</CustomField>

src/main/default/classes/DemoController.cls
public class DemoController {
    @AuraEnabled
    public static List<User> getUsers() {
        return [select name, id from User LIMIT 10];
    }
    @AuraEnabled
    public static List<Mascot__c> getMascots() {
        return [SELECT Biography__c,Contact__c,Id,Name,Picture__c FROM Mascot__c];
    }
    @AuraEnabled
    public static Mascot__c getMascot(String name) {
        return [SELECT Biography__c,Contact__c,Id,Name,Picture__c FROM Mascot__c WHERE Id = :name];
    }
    @AuraEnabled
    public static List<ListView> getContactLists() {
        return [SELECT Name,SobjectType FROM ListView WHERE SobjectType = 'Contact' ORDER BY Name ASC NULLS FIRST];
    }
}